import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {injected} from "../components/wallet/connectors"
import {useWeb3React} from "@web3-react/core"
export default function Home() {
const {active,account,library,connector,activate,deactivate}  =  useWeb3React()


async function connect(){
  try {
    await activate(injected)
  }
  catch(ex){
    console.log(ex)
  }

}

  return (
    <div className={styles.container}>
      <Head>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
       <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="style.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>

    <title>NiceFitTrip</title>
      </Head>

      <main className={styles.main}>
      <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">NiceFitTrip</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Map</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Meeting
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                  <li><a class="dropdown-item" href="#">Where Am I?</a></li>
                  <li><a class="dropdown-item" href="#">Where is current Meeting?</a></li>
                  <li><hr class="dropdown-divider"/></li>
                  <li><a class="dropdown-item" href="#">Current meet match.</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Go to OpenSea Page.</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search"/>
              <button class="btn btn-outline-success m-2" type="submit">Search</button>
            </form>
            <form>
              <button type="button" onClick={connect} class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Connect to wallet
              </button>
            </form>
          </div>
        </div>
      </nav><div class="title">
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Choose your wallet:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {active? <span>Connected with <b>{account}</b></span> : <span>Not connected</span>}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button onClick={disconnect}  type="button" class="btn btn-primary"></button>
      </div>
    </div>
  </div>
</div>

      </div>   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
      </main>
    </div>
  )
}
